* Overview
Gas mode is a major mode for editing assembly code with AT&T syntax,
usually code written to be executed by GAS (Gnu assembler).

* Install
First you need to clone this repository and move ~gas-menu.el~ file to
your load path and add the following code to your .emacs file:

#+BEGIN_SRC emacs-lisp
(require 'gas-mode)
(add-to-list 'auto-mode-alist '("\\.asm\\'" . gas-mode))
#+END_SRC

Now each time you open a file with ~.asm~ extension, gas-mode will be
use automatically.

* Customization
Variables can be changed through the customization menu or change its
value in your .emacs file.

** ~gas-initial-indentation~
This is an integer used to indent ~.section~ sections and tags to the
0 column by default but it can be changed to any other column you want.
** ~gas-indentation~
This is an integer use to indent any other lines not mentioned by the
previous variable, e.g. the instructions or directive lines.

* List of TODO improvements or features:

   - Improve indentation command to indent tags and .section to either
     the beginning of the line (depends on the value of `gas-initial-indent')
     or to the normal indentation (`gas-indentation') on the second time the
     command is executed.

   - Add blinking and indentation to some nested directives like ~.macro~.

   - Add support for company.

   - Add support for imenu.
